import type { Metadata } from "next";
import "./globals.css";
import {Header} from "@/_components/Header/Header";
import React from "react";


// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      {/*<script src="https://www.google.com/recaptcha/api.js" async defer></script>*/}

    </head>
      <body style={{height:'calc(108vh - 60px)'}} data-theme='dark'>
      <Header/>
      {children}
      </body>
    </html>
  );
}
